# Rails & Development Aliases
alias a='autotest -rails'
alias b="bundle"
alias be="bundle exec"
alias bi="bundle install --path vendor"
alias bil="bi --local"
alias binit="bi && bundle package && echo 'vendor/ruby' >> .gitignore"
alias bu="bundle update"
alias p='pry'
alias rc='rails c'
alias rd='rails destroy'
alias re='echo $RAILS_ENV'
alias rg='rails g'
alias rp='rails plugin'
alias rs='rails s'
alias sc='./script/console'
alias sd='./script/destroy'
alias sg='./script/generate'
alias sp='./script/plugin'
alias ss='./script/server'
