from colorama import Fore,Style,Back,init
init(autoreset=True)




print(Fore.GREEN + Style.BRIGHT + 'thursday, March 11, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'friday, March 12, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'monday, March 15, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'tuesday, March 16, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'wednesday, March 17, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'thursday, March 18, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'friday, March 19, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'saturday, March 20, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'tuesday, March 23, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'wednesday, March 24, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'Thursday, March 25, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'Sunday, March 28, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'Monday, March 29, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'Tuesday, March 30, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'Friday, April 2, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'Saturday, April 3, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'Sunday, April 4, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'Monday, April 5, 2021 - work')
print(Fore.GREEN + Style.BRIGHT + 'Tuesday, April 6, 2021 - alone coding')
print(Fore.GREEN + Style.BRIGHT + 'Wednesday, April 7, 2021 - sasebo park - workout')
print(Fore.GREEN + Style.BRIGHT + 'Thursday, April 8, 2021 - sasebo park - conding l w/ AN spears')
print(Fore.GREEN + Style.BRIGHT + 'Friday, April 9, 2021 - coding')
print(Fore.GREEN + Style.BRIGHT + 'Saturday, April 10, 2021 - coding')
print(Fore.GREEN + Style.BRIGHT + 'Sunday, April 11, 2021 - coding')
print(Fore.GREEN + Style.BRIGHT + 'Monday, April 12, 2021 - coding')
print(Fore.GREEN + Style.BRIGHT + 'Tuesday, April 13, 2021 - coding')
print(Fore.GREEN + Style.BRIGHT + 'Thursday, April 15, 2021 - coding')
print(Fore.GREEN + Style.BRIGHT + 'Friday, April 16, 2021 - coding')
print(Fore.GREEN + Style.BRIGHT + 'Saturday, April 17, 2021 - programmed for 19 hours')
print(Fore.GREEN + Style.BRIGHT + 'Saturday, April 25, 2021 - coding')
print(Fore.GREEN + Style.BRIGHT + 'Monday, April 26, 2021 - coding')
print(Fore.GREEN + Style.BRIGHT + 'Tuesday, April 27, 2021 - coding')
print(Fore.GREEN + Style.BRIGHT + 'Wednesday, April 28, 2021 - software updating and pushing updates')
print(Fore.GREEN + Style.BRIGHT + 'Thursday, April 29, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Friday, April 30, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Saturday, May 1, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Sunday, May 2, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Monday, May 3, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Tuesday, May 4, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Wednesday, May 5, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Thursday, May 6, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Friday, May 7, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Saturday, May 8, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Sunday, May 9, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Monday, May 10, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Tuesday, May 11, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Wednesday, May 12, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Thurday, May 13, 2021 - ROM')
print(Fore.GREEN + Style.BRIGHT + 'Friday, May 14, 2021 - coding')




print(Fore.GREEN + Style.BRIGHT + 'Monday, November 21, 2021 - banging with friends')
