#compdef autopep8
#
# this is zsh completion function file.
# generated by genzshcomp(ver: 0.5.1)
#

typeset -A opt_args
local context state line

_arguments -s -S \
  "--help[show this help message and exit]:" \
  "-h[show this help message and exit]:" \
  "--version[show program's version number and exit]:" \
  "--verbose[print verbose messages; multiple -v result in more verbose messages]" \
  "-v[print verbose messages; multiple -v result in more verbose messages]" \
  "--diff[print the diff for the fixed source]" \
  "-d[print the diff for the fixed source]" \
  "--in-place[make changes to files in place]" \
  "-i[make changes to files in place]" \
  "--recursive[run recursively; must be used with --in-place or --diff]" \
  "-r[run recursively; must be used with --in-place or --diff]" \
  "--jobs[number of parallel jobs; match CPU count if value is less than 1]::n        number of parallel jobs; match CPU count if value is:_files" \
  "-j[number of parallel jobs; match CPU count if value is less than 1]::n        number of parallel jobs; match CPU count if value is:_files" \
  "--pep8-passes[maximum number of additional pep8 passes (default: 100)]::n:_files" \
  "-p[maximum number of additional pep8 passes (default: 100)]::n:_files" \
  "-a[-a result in more aggressive changes]::result:_files" \
  "--exclude[exclude files/directories that match these comma- separated globs]::globs:_files" \
  "--list-fixes[list codes for fixes; used by --ignore and --select]" \
  "--ignore[do not fix these errors/warnings (default E226,E24)]::errors:_files" \
  "--select[fix only these errors/warnings (e.g. E4,W)]::errors:_files" \
  "--max-line-length[set maximum allowed line length (default: 79)]::n:_files" \
  "*::args:_files"
