alias ycr='yarn create redwood-app' # Creates a redwood project
alias yrb='yarn redwood build' # Builds for production
alias yrdb='yarn redwood dataMigrate' # Data migration tools
alias yrdev='yarn redwood dev' # Starts development servers for api and web
alias yrgencell='yarn redwood generate cell' # Generate a cell
alias yrdelcell='yarn redwood destroy cell' # Destory a cell
alias yrgencomp='yarn redwood generate component' # Generate a component
alias yrdelcomp='yarn redwood destroy component' # Destroy a component
alias yrgenmigrate='yarn redwood generate dataMigration' # Generates a data migration script
alias yrgendir='yarn redwood generate directive' # Generates a directive
alias yrdeldir='yarn redwood destroy directive' # Destroy a directive
alias yrgenfunc='yarn redwood generate function' # Generate a function
alias yrdelfunc='yarn redwood destroy function' # Destroy a function
alias yrgenlay='yarn redwood generate layout' # Generate a layout component
alias yrdellay='yarn redwood destroy layout' # Destroy a layout component
alias yrgenmod='yarn redwood generate model' # Generate a RedwoodRecord model
alias yrdelmod='yarn redwood destroy model' # Destroy a RedwoodRecord model
alias yrgenp='yarn redwood generate page' # Generates a page component and updates the routes
alias yrdelp='yarn redwood destroy page' # Destroys a page component
alias yrgensc='yarn redwood generate scaffold' # Generate Pages, SDL, and Serviecs based on a given DB schema model.
alias yrdelsc='yarn redwood destroy scaffold' # Destroys scaffold
alias yrgengql='yarn redwood generate sdl' # Generate GraphQL schema and service object
alias yrdelgql='yarn redwood destroy sdl' # Destroys GraphQL schema and service object
alias yrsecret='yarn redwood generate secret' # Generates a secret
alias yrgenser='yarn redwood generate service' # Generate a service component
alias yrdelser='yarn redwood destroy service' # Destroy a service component
alias yrgentype='yarn redwood generate types' # Generates supplemntary code (project types)
alias yrgenscript='yarn redwood generate script' # Generates script
alias yrinfo='yarn redwood info' # Prints system enviroment information
alias yrlint='yarn redwood lint' # Lint your files
alias yrpr='yarn redwood prisma' # Run Prisma CLI
