# jieryn@gmail.com

_mvn () {
  compadd ant:ant
  compadd ant:clean
  compadd ant:help
  compadd antlr3:antlr
  compadd antlr:generate
  compadd antlr:html
  compadd antrun:help
  compadd antrun:run
  compadd appassembler:assemble
  compadd appassembler:create-repository
  compadd appassembler:generate-daemons
  compadd appassembler:help
  compadd apt:eclipse
  compadd apt:process
  compadd apt:test-process
  compadd archetype:add-archetype-metadata
  compadd archetype:crawl
  compadd archetype:create
  compadd archetype:create-from-project
  compadd archetype:generate
  compadd archetype:help
  compadd archetype:integration-test
  compadd archetype:jar
  compadd archetype:update-local-catalog
  compadd aspectj:aspectj-report
  compadd aspectj:compile
  compadd aspectj:help
  compadd aspectj:test-compile
  compadd assembly:assembly
  compadd assembly:attached
  compadd assembly:directory
  compadd assembly:directory-inline
  compadd assembly:directory-single
  compadd assembly:help
  compadd assembly:single
  compadd assembly:unpack
  compadd axistools:admin
  compadd axistools:help
  compadd axistools:java2wsdl
  compadd axistools:wsdl2java
  compadd build-helper:add-resource
  compadd build-helper:add-source
  compadd build-helper:add-test-resource
  compadd build-helper:add-test-source
  compadd build-helper:attach-artifact
  compadd build-helper:help
  compadd build-helper:maven-version
  compadd build-helper:parse-version
  compadd build-helper:remove-project-artifact
  compadd build-helper:reserve-network-port
  compadd buildnumber:create
  compadd buildnumber:help
  compadd build-on-demand:help
  compadd build-on-demand:resolve
  compadd castor:generate
  compadd changelog:changelog
  compadd changelog:dev-activity
  compadd changelog:file-activity
  compadd changes:announcement-generate
  compadd changes:announcement-mail
  compadd changes:changes-report
  compadd changes:changes-validate
  compadd changes:help
  compadd changes:jira-report
  compadd changes:trac-report
  compadd checkstyle:check
  compadd checkstyle:checkstyle
  compadd checkstyle:help
  compadd clean:clean
  compadd clean:help
  compadd clirr:check
  compadd clirr:clirr
  compadd clirr:help
  compadd clover:aggregate
  compadd clover:check
  compadd clover:clover
  compadd clover:instrument
  compadd clover:instrumentInternal
  compadd clover:log
  compadd clover:save-history
  compadd cobertura:check
  compadd cobertura:clean
  compadd cobertura:cobertura
  compadd cobertura:dump-datafile
  compadd cobertura:instrument
  compadd commons-attributes:compile
  compadd commons-attributes:test-compile
  compadd compiler:compile
  compadd compiler:testCompile
  compadd continuum:add-ant-project
  compadd continuum:add-maven-one-project
  compadd continuum:add-maven-two-project
  compadd continuum:add-shell-project
  compadd continuum:ping
  compadd core-it:catch
  compadd core-it:fork
  compadd core-it:fork-goal
  compadd core-it:generate-envar-properties
  compadd core-it:generate-properties
  compadd core-it:light-touch
  compadd core-it:loadable
  compadd core-it:package
  compadd core-it:reachable
  compadd core-it:runnable
  compadd core-it:setter-touch
  compadd core-it:throw
  compadd core-it:touch
  compadd core-it:tricky-params
  compadd dashboard:dashboard
  compadd dashboard:persist
  compadd dbunit:compare
  compadd dbunit:export
  compadd dbunit:help
  compadd dbunit:operation
  compadd dependency:analyze
  compadd dependency:analyze-dep-mgt
  compadd dependency:analyze-only
  compadd dependency:analyze-report
  compadd dependency:build-classpath
  compadd dependency:copy
  compadd dependency:copy-dependencies
  compadd dependency:get
  compadd dependency:go-offline
  compadd dependency:help
  compadd dependency:list
  compadd dependency:purge-local-repository
  compadd dependency:resolve
  compadd dependency:resolve-plugins
  compadd dependency:sources
  compadd dependency:tree
  compadd dependency:unpack
  compadd dependency:unpack-dependencies
  compadd deploy-all:deploy-all
  compadd deploy-all:deploy-poms
  compadd deploy:deploy
  compadd deploy:deploy-file
  compadd deploy:help
  compadd doap:generate
  compadd doap:help
  compadd docbook:transform
  compadd docck:check
  compadd docck:help
  compadd ear:ear
  compadd ear:generate-application-xml
  compadd ear:help
  compadd eclipse:add-maven-repo
  compadd eclipse:clean
  compadd eclipse:configure-workspace
  compadd eclipse:eclipse
  compadd eclipse:help
  compadd eclipse:install-plugins
  compadd eclipse:m2eclipse
  compadd eclipse:make-artifacts
  compadd eclipse:myeclipse
  compadd eclipse:myeclipse-clean
  compadd eclipse:rad
  compadd eclipse:rad-clean
  compadd eclipse:remove-cache
  compadd eclipse:to-maven
  compadd ejb:ejb
  compadd ejb:help
  compadd emma:check
  compadd emma:clean
  compadd emma:emma
  compadd emma:help
  compadd emma:instrument
  compadd enforcer:display-info
  compadd enforcer:enforce
  compadd enforcer:enforce-once
  compadd enforcer:help
  compadd exec:exec
  compadd exec:help
  compadd exec:java
  compadd failsafe:help
  compadd failsafe:integration-test
  compadd failsafe:verify
  compadd findbugs:check
  compadd findbugs:findbugs
  compadd findbugs:gui
  compadd findbugs:help
  compadd fitnesse:fitnesse
  compadd fitnesse:remotecall
  compadd fitnesse:run
  compadd fit:run
  compadd gpg:sign
  compadd gpg:sign-and-deploy-file
  compadd groovy:compile
  compadd groovy:console
  compadd groovy:execute
  compadd groovy:generateStubs
  compadd groovy:generateTestStubs
  compadd groovy:help
  compadd groovy:providers
  compadd groovy:shell
  compadd groovy:testCompile
  compadd gwt:clean
  compadd gwt:compile
  compadd gwt:debug
  compadd gwt:eclipse
  compadd gwt:eclipseTest
  compadd gwt:generateAsync
  compadd gwt:help
  compadd gwt:i18n
  compadd gwt:mergewebxml
  compadd gwt:resources
  compadd gwt:run
  compadd gwt:sdkInstall
  compadd gwt:soyc
  compadd gwt:test
  compadd help:active-profiles
  compadd help:all-profiles
  compadd help:describe
  compadd help:effective-pom
  compadd help:effective-settings
  compadd help:evaluate
  compadd help:expressions
  compadd help:help
  compadd help:system
  compadd hibernate3:hbm2cfgxml
  compadd hibernate3:hbm2dao
  compadd hibernate3:hbm2ddl
  compadd hibernate3:hbm2doc
  compadd hibernate3:hbm2hbmxml
  compadd hibernate3:hbm2java
  compadd hibernate3:hbmtemplate
  compadd hibernate3:help
  compadd ianal:help
  compadd ianal:verify-legal-files
  compadd idea:clean
  compadd idea:help
  compadd idea:idea
  compadd idea:module
  compadd idea:project
  compadd ideauidesigner:javac2
  compadd idea:workspace
  compadd idlj:generate
  compadd idlj:generate-test
  compadd idlj:help
  compadd install:help
  compadd install:install
  compadd install:install-file
  compadd invoker:help
  compadd invoker:install
  compadd invoker:run
  compadd jalopy:format
  compadd jar:jar
  compadd jar:sign
  compadd jarsigner:help
  compadd jarsigner:sign
  compadd jarsigner:verify
  compadd jar:sign-verify
  compadd jar:test-jar
  compadd jasperreports:compile-reports
  compadd javacc:help
  compadd javacc:javacc
  compadd javacc:jjdoc
  compadd javacc:jjtree
  compadd javacc:jjtree-javacc
  compadd javacc:jtb
  compadd javacc:jtb-javacc
  compadd javadoc:aggregate
  compadd javadoc:aggregate-jar
  compadd javadoc:fix
  compadd javadoc:help
  compadd javadoc:jar
  compadd javadoc:javadoc
  compadd javadoc:test-aggregate
  compadd javadoc:test-aggregate-jar
  compadd javadoc:test-fix
  compadd javadoc:test-jar
  compadd javadoc:test-javadoc
  compadd javancss:check
  compadd javancss:help
  compadd javancss:report
  compadd jaxb2:xjc
  compadd jboss:configure
  compadd jboss:deploy
  compadd jboss:harddeploy
  compadd jboss:hardundeploy
  compadd jboss-packaging:esb
  compadd jboss-packaging:esb-exploded
  compadd jboss-packaging:har
  compadd jboss-packaging:har-exploded
  compadd jboss-packaging:help
  compadd jboss-packaging:par
  compadd jboss-packaging:sar
  compadd jboss-packaging:sar-exploded
  compadd jboss-packaging:sar-inplace
  compadd jboss-packaging:spring
  compadd jboss:redeploy
  compadd jboss:start
  compadd jboss:startAndWait
  compadd jboss:stop
  compadd jboss:undeploy
  compadd jdepend:generate
  compadd jpox:enhance
  compadd jpox:schema-create
  compadd jpox:schema-dbinfo
  compadd jpox:schema-delete
  compadd jpox:schema-info
  compadd jpox:schema-validate
  compadd jruby:run
  compadd jspc:compile
  compadd jspc:testCompile
  compadd jxr:jxr
  compadd jxr:test-jxr
  compadd keytool:clean
  compadd keytool:genkey
  compadd l10n:help
  compadd l10n:pseudo
  compadd l10n:report
  compadd local-config:check
  compadd local-config:configure
  compadd local-config:touch
  compadd make:autoreconf
  compadd make:chmod
  compadd make:chown
  compadd make:compile
  compadd make:configure
  compadd make:help
  compadd make:make-clean
  compadd make:make-dist
  compadd make:make-install
  compadd make:test
  compadd make:unpack
  compadd make:validate-pom
  compadd maven-one-plugin:convert
  compadd maven-one-plugin:deploy-maven-one-repository
  compadd maven-one-plugin:install-maven-one-repository
  compadd maven-one-plugin:maven-one-plugin
  compadd minijar:minijars
  compadd minijar:ueberjar
  compadd multibuild-optimizer:check-package-staleness
  compadd multibuild-optimizer:help
  compadd native2ascii:native2ascii
  compadd native:compile
  compadd native:compile-message
  compadd native:initialize
  compadd native:javah
  compadd native:link
  compadd native:ranlib
  compadd native:resource-compile
  compadd nbm:autoupdate
  compadd nbm:branding
  compadd nbm:cluster
  compadd nbm:cluster-app
  compadd nbm:help
  compadd nbm:manifest
  compadd nbm:nbm
  compadd nbm:populate-repository
  compadd nbm:run-ide
  compadd nbm:run-platform
  compadd nbm:standalone-zip
  compadd nbm:webstart-app
  compadd netbeans-freeform:generate-netbeans-project
  compadd openjpa:enhance
  compadd openjpa:help
  compadd openjpa:schema
  compadd openjpa:sql
  compadd osxappbundle:bundle
  compadd ounce:application
  compadd ounce:project
  compadd ounce:project-only
  compadd ounce:report
  compadd ounce:scan
  compadd patch:apply
  compadd patch:apply-directory
  compadd patch:get
  compadd patch:help
  compadd patch:package-patches
  compadd patch:purge-local-patch-artifact
  compadd patch:resolve-patches
  compadd pde:attach
  compadd pde:clean
  compadd pde:ext
  compadd pde:pde
  compadd pde:test
  compadd pdf:help
  compadd pdf:pdf
  compadd platform-detector:detect
  compadd platform-detector:help
  compadd plugin:addPluginArtifactMetadata
  compadd plugin:descriptor
  compadd plugin:help
  compadd plugin:helpmojo
  compadd plugin:report
  compadd plugin:updateRegistry
  compadd plugin:xdoc
  compadd pmd:check
  compadd pmd:cpd
  compadd pmd:cpd-check
  compadd pmd:pmd
  compadd project-archive:create
  compadd project-archive:deploy
  compadd project-archive:install
  compadd projecthelp:active-profiles
  compadd projecthelp:describe
  compadd projecthelp:effective-pom
  compadd projecthelp:effective-settings
  compadd project-info-reports:cim
  compadd project-info-reports:dependencies
  compadd project-info-reports:dependency-convergence
  compadd project-info-reports:dependency-management
  compadd project-info-reports:help
  compadd project-info-reports:index
  compadd project-info-reports:issue-tracking
  compadd project-info-reports:license
  compadd project-info-reports:mailing-list
  compadd project-info-reports:plugin-management
  compadd project-info-reports:plugins
  compadd project-info-reports:project-team
  compadd project-info-reports:scm
  compadd project-info-reports:summary
  compadd project-sources:deploy-project-sources
  compadd project-sources:help
  compadd project-sources:package-project-sources
  compadd project-sources:relocate
  compadd project-sources:resolve-project-sources
  compadd properties:help
  compadd properties:read-project-properties
  compadd properties:write-active-profile-properties
  compadd properties:write-project-properties
  compadd rar:rar
  compadd rat:check
  compadd rat:rat
  compadd reactor:help
  compadd reactor:make
  compadd reactor:make-dependents
  compadd reactor:make-scm-changes
  compadd reactor:resume
  compadd release:branch
  compadd release:clean
  compadd release:help
  compadd release:perform
  compadd release:prepare
  compadd release:rollback
  compadd release:stage
  compadd remote-resources:bundle
  compadd remote-resources:process
  compadd remote-source:get
  compadd remote-source:help
  compadd remote-source:relocate
  compadd remote-source:resolve
  compadd remote-source:unpack
  compadd repository:bundle-create
  compadd repository:bundle-pack
  compadd repository:help
  compadd resources:copy-resources
  compadd resources:help
  compadd resources:resources
  compadd resources:testResources
  compadd retrotranslator:help
  compadd retrotranslator:translate
  compadd retrotranslator:translate-project
  compadd retrotranslator:translate-war
  compadd rmic:help
  compadd rmic:package
  compadd rmic:rmic
  compadd rmic:test-rmic
  compadd rpm:attached-rpm
  compadd rpm-cbuild:build
  compadd rpm-cbuild:generate-spec
  compadd rpm-cbuild:help
  compadd rpm-cbuild:install
  compadd rpm-cbuild:install-dependencies
  compadd rpm-cbuild:platform-detect
  compadd rpm-cbuild:remove
  compadd rpm-cbuild:remove-project-references
  compadd rpm:help
  compadd rpm:rpm
  compadd rspec:spec
  compadd sablecc:generate
  compadd scm:add
  compadd scm:bootstrap
  compadd scm:branch
  compadd scm:changelog
  compadd scmchangelog:help
  compadd scmchangelog:report
  compadd scm:checkin
  compadd scm:check-local-modification
  compadd scm:checkout
  compadd scm:diff
  compadd scm:edit
  compadd scm:export
  compadd scm:help
  compadd scm:list
  compadd scm:status
  compadd scm:tag
  compadd scm:unedit
  compadd scm:update
  compadd scm:update-subprojects
  compadd scm:validate
  compadd selenium:help
  compadd selenium:selenese
  compadd selenium:start-server
  compadd selenium:stop-server
  compadd selenium:xvfb
  compadd settings:rsync
  compadd shade:help
  compadd shade:shade
  compadd shell:help
  compadd shell:shell
  compadd shitty:clean
  compadd shitty:help
  compadd shitty:install
  compadd shitty:test
  compadd site:attach-descriptor
  compadd site:deploy
  compadd site:help
  compadd site:jar
  compadd site:run
  compadd site:site
  compadd site:stage
  compadd site:stage-deploy
  compadd smc:smc
  compadd smc:smcreports
  compadd solaris:generate-prototype
  compadd solaris:package
  compadd solaris:resources
  compadd sonar:help
  compadd sonar:sonar
  compadd source:aggregate
  compadd source:help
  compadd source:jar
  compadd source:jar-no-fork
  compadd source:test-jar
  compadd source:test-jar-no-fork
  compadd springdoclet:springdoclet
  compadd springws:help
  compadd springws:springws
  compadd sql:execute
  compadd sql:help
  compadd sqlj:clean
  compadd sqlj:help
  compadd sqlj:sqlj
  compadd stage:copy
  compadd stage:help
  compadd surefire-report:report
  compadd surefire-report:report-only
  compadd surefire:test
  compadd sysdeo-tomcat:generate
  compadd sysdeo-tomcat:m2eclipse
  compadd taglist:help
  compadd taglist:taglist
  compadd tomcat:deploy
  compadd tomcat:deploy-only
  compadd tomcat:exploded
  compadd tomcat:help
  compadd tomcat:info
  compadd tomcat:inplace
  compadd tomcat:list
  compadd tomcat:redeploy
  compadd tomcat:reload
  compadd tomcat:resources
  compadd tomcat:roles
  compadd tomcat:run
  compadd tomcat:run-war
  compadd tomcat:sessions
  compadd tomcat:start
  compadd tomcat:stop
  compadd tomcat:undeploy
  compadd truezip:copy
  compadd truezip:help
  compadd truezip:list
  compadd truezip:move
  compadd truezip:remove
  compadd truezip:update
  compadd unix:dpkg-scanpackages
  compadd unix:help
  compadd unix:package-dpkg
  compadd unix:package-dpkg-attached
  compadd unix:package-pkg
  compadd unix:package-pkg-attached
  compadd unix:package-rpm
  compadd unix:package-rpm-attached
  compadd unix:package-zip
  compadd unix:package-zip-attached
  compadd verifier:verify
  compadd versions:commit
  compadd versions:dependency-updates-report
  compadd versions:display-dependency-updates
  compadd versions:display-dependency-updates-report
  compadd versions:display-plugin-updates
  compadd versions:help
  compadd versions:lock-snapshots
  compadd versions:resolve-ranges
  compadd versions:revert
  compadd versions:simple-report
  compadd versions:unlock-snapshots
  compadd versions:update-child-modules
  compadd versions:update-parent
  compadd versions:update-properties
  compadd versions:use-latest-releases
  compadd versions:use-latest-versions
  compadd versions:use-next-releases
  compadd versions:use-next-versions
  compadd versions:use-releases
  compadd wagon:copy
  compadd wagon:download
  compadd wagon:download-single
  compadd wagon:help
  compadd wagon:list
  compadd wagon:merge-maven-repos
  compadd wagon:upload
  compadd wagon:upload-single
  compadd war:exploded
  compadd war:help
  compadd war:inplace
  compadd war:manifest
  compadd war:war
  compadd was6:clean
  compadd was6:ejbdeploy
  compadd was6:help
  compadd was6:installApp
  compadd was6:servicedeploy
  compadd was6:wsAdmin
  compadd was6:wsDefaultBindings
  compadd was6:wsListApps
  compadd was6:wsStartApp
  compadd was6:wsStartServer
  compadd was6:wsStopApp
  compadd was6:wsStopServer
  compadd was6:wsUninstallApp
  compadd webdoclet:webdoclet
  compadd weblogic:appc
  compadd weblogic:clientgen
  compadd weblogic:clientgen9
  compadd weblogic:deploy
  compadd weblogic:jwsc
  compadd weblogic:listapps
  compadd weblogic:redeploy
  compadd weblogic:servicegen
  compadd weblogic:start
  compadd weblogic:stop
  compadd weblogic:undeploy
  compadd weblogic:wsdlgen
  compadd webstart:jnlp
  compadd webstart:report
  compadd xdoclet:xdoclet
  compadd xmlbeans:help
  compadd xmlbeans:xmlbeans
  compadd xmlbeans:xmlbeans-test
  compadd xml:transform
  compadd xml:validate
  compadd xslt:transform
}

compdef _mvn mvn
