#!/bin/sh

url="https://raw.githubusercontent.com/felipec/git-completion"
version="1.0"

curl -s -o _git "${url}/v${version}/git-completion.zsh" &&
curl -s -o git-completion.bash "${url}/v${version}/git-completion.bash" &&
curl -s -o git-prompt.sh "${url}/v${version}/git-prompt.sh"
