alias kube="kubectl"
alias kc="kubectl"
alias mk="minikube"
alias kube-list-contexts="kubectl config get-contexts"
alias docker-suicide="killall com.docker.hyperkit"
alias docker-die="killall com.docker.hyperkit"
alias mk="minikube"
