# common functions
alias d-a='sudo /DietPi/dietpi/dietpi-autostart'
alias d-b='sudo /DietPi/dietpi/dietpi-backup'
alias d-ba='/DietPi/dietpi/func/dietpi-banner'
alias d-c='sudo /DietPi/dietpi/dietpi-config'
alias d-cl='sudo /DietPi/dietpi/func/dietpi-logclear'
alias d-cs='sudo /DietPi/dietpi/dietpi-cloudshell'
alias d-d='sudo /DietPi/dietpi/dietpi-drive_manager'
alias d-ds='sudo /Dietpi/dietpi/func/set_dphys-swapfile'
alias d-e='sudo /DietPi/dietpi/dietpi-explorer'
alias d-g='sudo /Dietpi/dietpi/func/set_cpu'
alias d-h='sudo /DietPi/dietpi/dietpi-cpuinfo'
alias d-help='cat ~/.oh-my-zsh/plugins/dietpi/README.md'
alias d-i='sudo /DietPi/dietpi/dietpi-software'
alias d-l='sudo /DietPi/dietpi/dietpi-launcher'
alias d-lc='sudo /DietPi/dietpi/dietpi-letsencrypt'
alias d-ld='sudo /DietPi/dietpi/func/dietpi-led_control'
alias d-m='sudo /DietPi/dietpi/dietpi-morsecode'
alias d-n='sudo /DietPi/dietpi/dietpi-cron'
alias d-o='DietPi/dietpi/func/dietpi-optimal_mtu'
alias d-p='sudo /DietPi/dietpi/dietpi-process_tool'
alias d-r='sudo /DietPi/dietpi/dietpi-sync'
alias d-s='sudo /DietPi/dietpi/dietpi-services'
alias d-sac='sudo /DietPi/dietpi/dietpi-services systemd_controlled && sudo /DietPi/dietpi/dietpi-services dietpi_controlled'
alias d-sad='sudo /DietPi/dietpi/dietpi-services disable all'
alias d-sae='sudo /DietPi/dietpi/dietpi-services enable all'
alias d-ss='sudo /DietPi/dietpi/dietpi-services status'
alias d-sr='sudo /DietPi/dietpi/dietpi-services restart'
alias d-su='sudo /DietPi/dietpi/dietpi-services unmask'
alias d-sm='sudo /DietPi/dietpi/dietpi-services mask'
alias d-t='sudo /DietPi/dietpi/dietpi-cleaner'
alias d-u='sudo /DietPi/dietpi/dietpi-update'

# Last but not least print the login message
/DietPi/dietpi/login
