alias mp="multipass"
alias mpla="multipass launch"
alias mpl="multipass list"
alias mpsp="multipass stop"
alias mpst="multipass start"
alias mps="multipass shell"
alias mpln="multipass launch --network en0 --network name=bridge0,mode=manual"
