alias bc="brew cleanup"
alias bci="brew cask info"
alias bcl="brew cask list"
alias bco="brew cask outdated"
alias bcu="brew cask upgrade"
alias bl="brew list"
alias bo="brew outdated"
alias bu="brew update"
alias brewp='brew pin'
alias brews='bl -1'
alias brewsp='bl --pinned'
alias bubo='bu && bo'
alias bubc='brew upgrade && bc'
alias bubu='bubo && bubc'
alias bcubo='bu && bco'
alias bubobco='bubo && bco'
alias bcubc='brew cask reinstall $(bco) && bc'