alias di='docker info'
alias dlg='docker container logs'
alias dls='docker container ls'
alias dlsa='docker container ls -a'
alias dr='docker container run'
alias drm='docker container rm'
alias drmf='docker container rm -f'
alias ds='docker container stop'
alias dt='docker top'
alias dv='docker version'
alias dpo='docker container port'
alias dpu='docker pull'
alias dx='docker exec'
alias dbl='docker build'
alias dhh='docker help'

#docker images
alias dirm='docker image rm'
alias dils='docker image ls'
