di='docker info'
dlg='docker container logs'
dls='docker container ls'
dlsa='docker container ls -a'
dr='docker container run'
drm='docker container rm'
drmf='docker container rm -f'
ds='docker container stop'
dt='docker top'
dv='docker version'
dpo='docker container port'
dpu='docker pull'
dx='docker exec'
dbl='docker build'
dhh='docker help'

#docker images
dirm='docker image rm'
dils='docker image ls'