alias mvni='mvn clean install'
alias mvnis='mvn clean install -DskipTests=true'
alias mvntf='mvn clean install -pl antq-store-file'
alias mvnd='mvn clean deploy -DskipTests=true'
alias mvnv='mvn -version'
alias pull='git pull origin master'
alias push='git push origin master'
alias gpo='git push origin '
alias gpl='git pull origin '
alias gcob='gco -b'
alias tailf='tail -f'
