alias pmr='python manage.py runserver'
alias pmrp='python manage.py runserver_plus'
alias pmrpg='pmrp --adminmedia=`pwd`/media/admin'
alias pmsdb='python manage.py syncdb'
alias pms='python manage.py shell'
alias pmlf='python manage.py loaddata fixtures/*'
