alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias ls='ls -F --color=auto'
alias ll='ls -l'
alias grep='grep --color=auto'
alias ee='emacsclient -t'
alias history='history -fi'
alias diff='diff -u'
alias v='vim'
alias s='subl'
