# Autogenerated from ng help 
ng_opts='xi18n version update test serve run new lint help generate e2e doc config deploy build analytics add '
add_opts='--verbose --registry --interactive --help --defaults '
analytics_opts='--help '
build_opts='--web-worker-ts-config --watch --verbose --vendor-source-map --vendor-chunk --ts-config --subresource-integrity --stats-json --source-map --skip-app-shell --show-circular-dependencies --service-worker --resources-output-path --rebase-root-relative-css-urls --progress --profile --configuration --prod --preserve-symlinks --polyfills --poll --output-path --output-hashing --optimization --ngsw-config-path --named-chunks --main --localize --lazy-modules --index --i18n-missing-translation --i18n-locale --i18n-file --i18n-format --i18n-file --help --fork-type-checker --extract-licenses --extract-css --experimental-rollup-pass --eval-source-map --es5-browser-support --deploy-url --delete-output-path --cross-origin --prod --configuration --common-chunk --build-optimizer --build-event-log --base-href --aot '
deploy_opts='--help '
config_opts='--help --global '
doc_opts='--version --search --help '
e2e_opts='--webdriver-update --suite --specs --protractor-config --configuration --prod --port --invert-grep --host --help --grep --element-explorer --dev-server-target --prod --configuration --base-url '
generate_opts='--interactive --help --force --dry-run webWorker--defaults serviceWorker service pipe module library interface interceptor guard enum directive component class application appShell '
help_opts='--help '
lint_opts='--type-check --tslint-config --ts-config --silent --help --format --force --fix --files --exclude --configuration '
new_opts='--view-encapsulation --verbose --style --strict --skip-tests --skip-install --skip-git --routing --prefix --package-manager --new-project-root --minimal --interactive --inline-template --inline-style --help --force --dry-run --directory --defaults --create-application --commit --collection '
run_opts='--help --configuration '
serve_opts='--watch --verbose --vendor-source-map --vendor-chunk --ssl-key --ssl-cert --ssl --source-map --serve-path-default-warning --serve-path --public-host --proxy-config --progress --configuration --prod --port --poll --optimization --open --live-reload --host --hmr --hmr-warning --hmr --help --eval-source-map --disable-host-check --deploy-url --prod --configuration --common-chunk --build-event-log --browser-target --base-href --aot --allowed-hosts '
test_opts='--web-worker-ts-config --watch --vendor-source-map --ts-config --source-map --reporters --progress --configuration --prod --preserve-symlinks --polyfills --poll --main --karma-config --include --help --eval-source-map --environment --prod --configuration --code-coverage-exclude --code-coverage --browsers '
update_opts='--verbose --to --packages --next --migrate-only --help --from --force --create-commits --allow-dirty --all '
version_opts='--help '
xi18n_opts='--progress --configuration --prod --output-path --out-file --i18n-locale --i18n-format --help --format --prod --configuration --browser-target '
_ng_completion () {
  local words cword opts
  read -Ac words
  read -cn cword
  let cword-=1

  case $words[2] in
    add )
      opts=$add_opts
      ;;

    analytics )
      opts=$analytics_opts
      ;;

    b | build )
      opts=$build_opts
      ;;

    deploy )
      opts=$deploy_opts
      ;;

    config )
      opts=$config_opts
      ;;

    doc | d )
      opts=$doc_opts
      ;;

    e2e | e )
      opts=$e2e_opts
      ;;

    generate | g)
      opts=$generate_opts
      ;;

    help )
      opts=$help_opts
      ;;

    lint | l )
      opts=$lint_opts
      ;;

    new | n )
      opts=$new_opts
      ;;

    run)
      opts=$run_opts
      ;;

    serve | s )
      opts=$serve_opts
      ;;

    test | t )
      opts=$test_opts
      ;;

    update )
      opts=$update_opts
      ;;

    version | v )
      opts=$version_opts
      ;;

    xi18n | i18n-extract )
      opts=$xi18n_opts
      ;;

    * )
      case $words[1] in
        ng )
          opts=$ng_opts
          ;;
        * )
          opts=''
          ;;
      esac
  esac

  reply=(${=opts})
}

compctl -K _ng_completion ng
