alias ca="conda activate"
alias cab="conda activate base"
alias cde="conda deactivate"
alias cel="conda env list"
alias cl="conda list"
alias cle="conda list --export"
alias cles="conda list --explicit > spec-file.txt"

alias ci="conda install"
alias ciy="conda install -y"
alias cr="conda remove"
alias cry="conda remove -y"
alias ccn="conda create -y -n"
alias ccp="conda create -y -p"
alias ccf="conda env create -f"
alias crn="conda remove -y --all -n"
alias crp="conda remove -y --all -p"

alias cconf="conda config"
alias ccss="conda config --show-source"
alias cu="conda update"
alias cuc="conda update conda"
alias cua="conda update --all"
