# Comment

PROMPT='%F{magenta}[%c] %f'

RPROMPT='%F{magenta}$(git_prompt_info)%f $(git_prompt_status)%f'

ZSH_THEME_GIT_PROMPT_PREFIX=""
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_DIRTY=""
ZSH_THEME_GIT_PROMPT_CLEAN=""
ZSH_THEME_GIT_PROMPT_ADDED="%F{cyan} ✈"
ZSH_THEME_GIT_PROMPT_MODIFIED="%F{yellow} ✭"
ZSH_THEME_GIT_PROMPT_DELETED="%F{red} ✗"
ZSH_THEME_GIT_PROMPT_RENAMED="%F{blue} ➦"
ZSH_THEME_GIT_PROMPT_UNMERGED="%F{magenta} ✂"
ZSH_THEME_GIT_PROMPT_UNTRACKED="%F{grey} ✱"
