# React Native
alias rn='react-native'
alias rns='react-native start'
alias rnlink='react-native link'
alias rnland='react-native log-android'
alias rnlios='react-native log-ios'
alias rnand='react-native run-android'
alias rnios='react-native run-ios'

# iPhone
alias rnios4s='react-native run-ios --simulator "iPhone 4s"'
alias rnios5='react-native run-ios --simulator "iPhone 5"'
alias rnios5s='react-native run-ios --simulator "iPhone 5s"'
alias rnios6='react-native run-ios --simulator "iPhone 6"'
alias rnios6p='react-native run-ios --simulator "iPhone 6 Plus"'
alias rnios6s='react-native run-ios --simulator "iPhone 6s"'
alias rnios6sp='react-native run-ios --simulator "iPhone 6s Plus"'
alias rnios7='react-native run-ios --simulator "iPhone 7"'
alias rnios7p='react-native run-ios --simulator "iPhone 7 Plus"'
alias rnios8='react-native run-ios --simulator "iPhone 8"'
alias rnios8p='react-native run-ios --simulator "iPhone 8 Plus"'
alias rniosse='react-native run-ios --simulator "iPhone SE"'
alias rniosx='react-native run-ios --simulator "iPhone X"'
alias rniosxs='react-native run-ios --simulator "iPhone Xs"'
alias rniosxsm='react-native run-ios --simulator "iPhone Xs Max"'
alias rniosxr='react-native run-ios --simulator "iPhone Xʀ"'

# iPad
alias rnipad2='react-native run-ios --simulator "iPad 2"'
alias rnipad5='react-native run-ios --simulator "iPad (5th generation)"'
alias rnipad6='react-native run-ios --simulator "iPad (6th generation)"'
alias rnipadr='react-native run-ios --simulator "iPad Retina"'
alias rnipada='react-native run-ios --simulator "iPad Air"'
alias rnipada2='react-native run-ios --simulator "iPad Air 2"'
alias rnipada3='react-native run-ios --simulator "iPad Air (3rd generation)"'
alias rnipadm2='react-native run-ios --simulator "iPad mini 2"'
alias rnipadm3='react-native run-ios --simulator "iPad mini 3"'
alias rnipadm4='react-native run-ios --simulator "iPad mini 4"'
alias rnipadm5='react-native run-ios --simulator "iPad mini (5th generation)"'
alias rnipadp9='react-native run-ios --simulator "iPad Pro (9.7-inch)"'
alias rnipadp12='react-native run-ios --simulator "iPad Pro (12.9-inch)"'
alias rnipadp122='react-native run-ios --simulator "iPad Pro (12.9-inch) (2nd generation)"'
alias rnipadp10='react-native run-ios --simulator "iPad Pro (10.5-inch)"'
alias rnipad11='react-native run-ios --simulator "iPad Pro (11-inch)"'
alias rnipad123='react-native run-ios --simulator "iPad Pro (12.9-inch) (3rd generation)"'

# Apple TV
alias rnatv='react-native run-ios --simulator "Apple TV"'
alias rnatv4k='react-native run-ios --simulator "Apple TV 4K"'
alias rnatv4k1080='react-native run-ios --simulator "Apple TV 4K (at 1080p)"'

# Apple Watch
alias rnaw38='react-native run-ios --simulator "Apple Watch - 38mm"'
alias rnaw42='react-native run-ios --simulator "Apple Watch - 42mm"'
alias rnaws238='react-native run-ios --simulator "Apple Watch Series 2 - 38mm"'
alias rnaws242='react-native run-ios --simulator "Apple Watch Series 2 - 42mm"'
alias rnaws338='react-native run-ios --simulator "Apple Watch Series 3 - 38mm"'
alias rnaws342='react-native run-ios --simulator "Apple Watch Series 3 - 42mm"'
alias rnaws440='react-native run-ios --simulator "Apple Watch Series 4 - 40mm"'
alias rnaws444='react-native run-ios --simulator "Apple Watch Series 4 - 44mm"'
