alias rn='react-native'
alias rns='react-native start'
alias rnlink='react-native link'

alias rnand='react-native run-android'
alias rnios='react-native run-ios'
alias rnios4s='react-native run-ios --simulator "iPhone 4s"'
alias rnios5='react-native run-ios --simulator "iPhone 5"'
alias rnios5s='react-native run-ios --simulator "iPhone 5s"'
alias rnios6='react-native run-ios --simulator "iPhone 6"'
alias rnios6s='react-native run-ios --simulator "iPhone 6s"'
alias rnios7='react-native run-ios --simulator "iPhone 7"'
alias rnios7p='react-native run-ios --simulator "iPhone 7 Plus"'
alias rnios8='react-native run-ios --simulator "iPhone 8"'
alias rnios8p='react-native run-ios --simulator "iPhone 8 Plus"'
alias rniosse='react-native run-ios --simulator "iPhone SE"'
alias rniosx='react-native run-ios --simulator "iPhone X"'
alias rniosxs='react-native run-ios --simulator "iPhone XS"'
alias rniosxsm='react-native run-ios --simulator "iPhone XS Max"'
alias rniosxr='react-native run-ios --simulator "iPhone XR"'

alias rnipad2='react-native run-ios --simulator "iPad 2"'
alias rnipadr='react-native run-ios --simulator "iPad Retina"'
alias rnipada='react-native run-ios --simulator "iPad Air"'
alias rnipada2='react-native run-ios --simulator "iPad Air 2"'
alias rnipad5='react-native run-ios --simulator "iPad (5th generation)"'
alias rnipad9='react-native run-ios --simulator "iPad Pro (9.7-inch)"'
alias rnipad12='react-native run-ios --simulator "iPad Pro (12.9-inch)"'
alias rnipad122='react-native run-ios --simulator "iPad Pro (12.9-inch) (2nd generation)"'
alias rnipad10='react-native run-ios --simulator "iPad Pro (10.5-inch)"'
alias rnipad6='react-native run-ios --simulator "iPad Pro (6th generation)"'
alias rnipad11='react-native run-ios --simulator "iPad Pro (11-inch)"'
alias rnipad123='react-native run-ios --simulator "iPad Pro (12.9-inch) (3rd generation)"'

alias rnatv='react-native run-ios --simulator "Apple TV"'
alias rnatv4k='react-native run-ios --simulator "Apple TV 4K"'
alias rnatv4k1080='react-native run-ios --simulator "Apple TV 4K (at 1080p)"'

alias rnland='react-native log-android'
alias rnlios='react-native log-ios'
