name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    if: github.repository == 'ohmyzsh/ohmyzsh'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Set up git repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh
      - name: Check syntax
        run: |
          for file in ./oh-my-zsh.sh \
                      ./lib/*.zsh \
                      ./plugins/*/*.plugin.zsh \
                      ./plugins/*/_* \
                      ./themes/*.zsh-theme; do
            zsh -n "$file" || return 1
          done
