#Aliases
alias pc="sudo port clean --all installed"
alias pi="sudo port install $1"
alias psu="sudo port selfupdate"
alias puni="sudo port uninstall inactive"
alias puo="sudo port upgrade outdated"
alias pup="psu && puo"
alias prm="sudo port uninstall --follow-dependencies $1"
alias pq="port search $1"
alias pqb="port provides $1"
alias pqf="port contents $1"
alias pvar="port variants $1"
